In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('train.txt',sep=';',names=['text','emotion'])

df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
unique_emotion = df['emotion'].unique()
unique_emotion

<ArrowStringArray>
['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']
Length: 6, dtype: str

In [6]:
emotion = {}

for i,em in enumerate(unique_emotion):
    emotion[em] = i

emotion

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [8]:
df['emotion'] = df['emotion'].map(emotion)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

### Text cleaning and preprocessing