In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('train.txt',sep=';',names=['text','emotion'])

df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
unique_emotion = df['emotion'].unique()
unique_emotion

<ArrowStringArray>
['sadness', 'anger', 'love', 'surprise', 'fear', 'joy']
Length: 6, dtype: str

In [6]:
emotion = {}

for i,em in enumerate(unique_emotion):
    emotion[em] = i

emotion

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [8]:
df['emotion'] = df['emotion'].map(emotion)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

### Text cleaning and preprocessing

In [9]:
df['text'] = df['text'].apply(lambda x:x.lower())

In [11]:
# removing digits
def remove_digit(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new += i

    return new


df['text'] = df['text'].apply(remove_digit)

In [12]:
def remove_emoji(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i

    return new

df['text'] = df['text'].apply(remove_emoji)

In [13]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))


df['text'] = df['text'].apply(remove_punc)

In [14]:
import nltk

nltk.download("stopwords")

[nltk_data] Downloading package stopwords to C:\Users\ZAM ZAM
[nltk_data]     LAPTOP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [15]:
from nltk.corpus import stopwords

# Download once
# import nltk
# nltk.download("stopwords")

stop_words = set(stopwords.words("english"))

def remove_stopword(text):
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return " ".join(filtered_words)

In [16]:
df["text"] = df["text"].apply(remove_stopword)

In [17]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1